/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.org.lidalia.jpmsapp.kotlin-library-conventions")
}

dependencies {
    api(project(":list"))
}

tasks.withType<JavaCompile> {
    options.compilerArgs = listOf(
        "--patch-module", "uk.org.lidalia.jpmsapp.utilities=${sourceSets.main.get().output.asPath}"
    )
}
