/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.org.lidalia.jpmsapp.kotlin-library-conventions")
}

val moduleName by extra("uk.org.lidalia.jpmsapp.utilities")

dependencies {
    api(project(":list"))
}

tasks.withType<JavaCompile> {
    inputs.property("moduleName", moduleName)
    options.compilerArgs = listOf(
        "--patch-module", "$moduleName=${sourceSets.main.get().output.asPath}"
    )
}
